import Head from "next/head";
import FooterPlayList from "@components/FooterPlayer";
import TopBar from "@components/TopBar";
import { Charts } from "@store/slices/Charts";
import SliderContainer from "@components/SliderContainer";
import { useAppTheme } from "@context/ThemeContext";

import styles from "../styles/Home.module.css";
import withAsync from "./api/api";
import { getChartsData } from "./api/charts";
import { getChartsDataByGenre } from "./api/genre";

export default function Home({
  charts,
  popgenre,
}: {
  charts: Charts[];
  popgenre: Charts[];
}) {
  const { theme } = useAppTheme();

  const handleClick = (song:Charts) => {
    console.log(song)
  }

  return (
    <div data-theme={theme}>
      <Head>
        <title>Muzik App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <TopBar />

        <SliderContainer playlist={charts} title='Top Charts' onClick={handleClick}/>
        <SliderContainer playlist={popgenre} title='Pop Music' />

        <FooterPlayList />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  // withAsync({
  //   method: "GET",
  //   url: "charts/country",
  //   params: { country_code: "IN" },
  // })
  const [charts, popgenre] = await Promise.allSettled([
    getChartsData(),
    getChartsDataByGenre(),
  ]);

  return {
    props: {
      charts: charts.status === "fulfilled" ? charts.value : charts.reason,
      popgenre:
        popgenre.status === "fulfilled" ? popgenre.value : popgenre.reason,
    },
  };
}
